---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-kiwithon-com
  namespace: myapp
spec:
  secretName: local-kiwithon-com-stagingtest-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.kiwithon.com"
  dnsNames:
  - "local.kiwithon.com"
  - "*.local.kiwithon.com"
